######################################################
# Install Teleport
######################################################
- name: Add Teleport GPG key
  ansible.builtin.apt_key:
    url: "{{ teleport_gpg_key }}"
    state: present

- name: Add Teleport APT repo
  ansible.builtin.apt_repository:
    repo: "{{ teleport_apt_repo }}"
    state: present

- name: Install Teleport
  ansible.builtin.apt:
    name: "teleport"
    state: latest

######################################################
# Setup Teleport
######################################################
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/teleport.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Teleport config
  ansible.builtin.template:
    src: "templates/teleport.yaml.j2"
    dest: "/etc/teleport.yaml"
    owner: root
    group: root
    mode: 0600

- name: Start Teleport
  ansible.builtin.service:
    name: "teleport"
    state: restarted
    enabled: true

######################################################
# Setup roles
######################################################
- name: Copy role templates
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/teleport.d/{{ item | basename }}"
    owner: root
    group: root
    mode: 0400
  loop: "{{ teleport_roles_templates }}"

- name: Create role with tctl
  ansible.builtin.command: "tctl create -f /etc/teleport.d/{{ item | basename }}"
  register: tctlrole
  changed_when:
    - "'has been created' in tctlrole.stdout"
  loop: "{{ teleport_roles_templates }}"

######################################################
# Setup Github SSO
# https://goteleport.com/docs/access-controls/sso/github-sso/
######################################################
- name: Github SSO
  when:
    - teleport_auth_type == 'github'
    - github_org_name|string
    - github_client_id|string
    - github_client_secret|string
  block:
    - name: Copy Github config
      ansible.builtin.template:
        src: "templates/github.yaml.j2"
        dest: "/etc/teleport.d/github.yaml"
        owner: root
        group: root
        mode: 0600

    - name: Create Github connector
      ansible.builtin.command: "tctl create -f /etc/teleport.d/github.yaml"

    - name: Copy cap config
      ansible.builtin.template:
        src: "templates/cap.yaml.j2"
        dest: "/etc/teleport.d/cap.yaml"
        owner: root
        group: root
        mode: 0600

    - name: Create cluster auth preferences
      ansible.builtin.command: "tctl create -f /etc/teleport.d/cap.yaml"

######################################################
# Healthcheck Teleport
######################################################
- name: Teleport Health Check - local port
  ansible.builtin.wait_for:
    port: "{{ item }}"
    delay: 10
    timeout: 300
  loop: [443, 3022, 3025]

- name: Teleport Health Check - web fqdn
  ansible.builtin.wait_for:
    host: "{{ teleport_fqdn }}"
    port: "{{ item }}"
    delay: 10
    timeout: 300
  loop: [443]
