######################################################
# Install Teleport
######################################################
- name: Add Teleport GPG key
  ansible.builtin.apt_key:
    url: "{{ teleport_gpg_key }}"
    state: present

- name: Add Teleport APT repo
  ansible.builtin.apt_repository:
    repo: "{{ teleport_apt_repo }}"
    state: present

- name: Install Teleport
  ansible.builtin.apt:
    name: "teleport"
    state: latest

######################################################
# Setup Teleport
######################################################
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/teleport.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy Teleport config
  ansible.builtin.template:
    src: "templates/teleport.yaml.j2"
    dest: "/etc/teleport.yaml"
    owner: root
    group: root
    mode: '0600'

- name: Start Teleport
  ansible.builtin.service:
    name: "teleport"
    state: restarted
    enabled: true

######################################################
# Setup roles
######################################################
- name: Copy role templates
  ansible.builtin.template:
    src: "{{ teleport_cluster_item }}.j2"
    dest: "/etc/teleport.d/{{ teleport_cluster_item | basename }}"
    owner: root
    group: root
    mode: '0400'
  loop: "{{ teleport_roles_templates }}"
  loop_control:
    loop_var: teleport_cluster_item

- name: Create role with tctl
  ansible.builtin.command: "tctl create -f /etc/teleport.d/{{ teleport_cluster_item | basename }}"
  register: tctlrole
  changed_when:
    - "'has been created' in tctlrole.stdout"
  loop: "{{ teleport_roles_templates }}"
  loop_control:
    loop_var: teleport_cluster_item
  when:
    - teleport_auth_online | bool

######################################################
# Setup local users if local authentication
# https://goteleport.com/docs/management/admin/users/#adding-local-users
######################################################
- name: Local Authentication
  when:
    - teleport_auth_type == 'local'
    - teleport_auth_online | bool
  block:
    - name: Create local users with tctl
      ansible.builtin.command: |
        tctl users add {{ teleport_cluster_item.username }}
          --logins={{ teleport_cluster_item.logins | join(',') }}
          --roles={{ teleport_cluster_item.roles | join(',') }}
      register: tctlusers
      changed_when:
        - tctlusers.rc == 0
        - "'already registered' not in tctlusers.stderr"
      failed_when:
        - tctlusers.rc != 0
        - "'already registered' not in tctlusers.stderr"
      loop: "{{ teleport_auth_local_users }}"
      loop_control:
        loop_var: teleport_cluster_item

######################################################
# Setup Github SSO
# https://goteleport.com/docs/access-controls/sso/github-sso/
######################################################
- name: Github SSO
  when:
    - teleport_auth_type == 'github'
    - github_org_name|string
    - github_client_id|string
    - github_client_secret|string
  block:
    - name: Copy Github config
      ansible.builtin.template:
        src: "templates/github.yaml.j2"
        dest: "/etc/teleport.d/github.yaml"
        owner: root
        group: root
        mode: '0600'

    - name: Create Github connector
      ansible.builtin.command: "tctl create -f /etc/teleport.d/github.yaml"
      when:
        - teleport_auth_online | bool

    - name: Copy cap config
      ansible.builtin.template:
        src: "templates/cap.yaml.j2"
        dest: "/etc/teleport.d/cap.yaml"
        owner: root
        group: root
        mode: '0600'

    - name: Create cluster auth preferences
      ansible.builtin.command: "tctl create -f /etc/teleport.d/cap.yaml"
      when:
        - teleport_auth_online | bool

######################################################
# Healthcheck Teleport
######################################################
- name: Teleport Health Check - local port
  ansible.builtin.wait_for:
    port: "{{ teleport_cluster_item }}"
    delay: 10
    timeout: 300
  loop: [443, 3022, 3025]
  loop_control:
    loop_var: teleport_cluster_item

- name: Teleport Health Check - web fqdn
  ansible.builtin.wait_for:
    host: "{{ teleport_fqdn }}"
    port: "{{ teleport_cluster_item }}"
    delay: 10
    timeout: 300
  loop: [443]
  loop_control:
    loop_var: teleport_cluster_item
  when:
    - teleport_auth_online | bool
