---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: requirements-txt-fixer


  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black


  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88']


  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.0b0
    hooks:
      - id: pylint


  - repo: https://github.com/ansible/ansible-lint
    rev: v6.11.0
    hooks:
      - id: ansible-lint
        files: ^ansible/

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
